apiVersion: v1                                      # API version
kind: Service                                       # Type of kubernetes resource 
metadata:
  name: test-postgres-db-external                   # Name of the resource
  namespace: pgo
  labels:                                           # Labels that will be applied to the resource
    app: test-postgres-db
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:                                         # Selects any Pod with labels `app=fullstack-postgres,tier=postgres`
    app: test-postgres-db
    tier: postgres
---
apiVersion: v1                                      # API version
kind: Service                                       # Type of kubernetes resource 
metadata:
  name: test-postgres-db-internal                         # Name of the resource
  namespace: pgo
  labels:                                           # Labels that will be applied to the resource
    app: test-postgres-db
spec:
  ports:
    - port: 5432
  selector:                                         # Selects any Pod with labels `app=fullstack-postgres,tier=postgres`
    app: test-postgres-db
    tier: postgres    