apiVersion: v1                                      # API version
kind: Service                                       # Type of kubernetes resource 
metadata:
  name: spark-postgres-db                          # Name of the resource
  namespace: pgo
  labels:                                           # Labels that will be applied to the resource
    app: spark-postgres-db
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:                                         # Selects any Pod with labels `app=fullstack-postgres,tier=postgres`
    app: spark-postgres-db
    tier: postgres